---
layout: page
title: "전쟁과 인공지능"
subtitle: "국방은 데이터 과학과 인공지능"
author:
  name: "[한국 R 사용자회](https://r2bit.com/)"
date: "2022-07-22"
output:
  html_document: 
    theme:
      version: 4
    toc: yes
    toc_depth: 2
    toc_float: true
    highlight: tango
    code_folding: show
    number_section: true
    self_contained: true
urlcolor: blue
linkcolor: bluee
editor_options: 
  chunk_output_type: console
  markdown: 
    wrap: sentence
---

```{r, include=FALSE}
# source("tools/chunk-options.R")
knitr::opts_chunk$set(echo = FALSE, warning=FALSE, message=FALSE,
                    comment="", digits = 3, tidy = FALSE, prompt = FALSE, fig.align = 'center')

library(here)
```


# 학습목차


```{r deep-learing-list}
library(tidyverse)
library(bs4cards)

military_list <- list(
  tibble(
    title = "군함",
    image = "fig/favicon-battleship.png",
    text = "드레드노트, 항공모함, 잠수함, ...",
    link = "battleship.html",
    footer = "2022-06-28"
  )  
)


military_tbl <- military_list %>% 
  enframe() %>% 
  unnest(value)

military_tbl %>% 
  cards(
    title = title,
    text = text,
    link = link,
    image = image,
    footer = footer,
    layout = "label-left", 
    width = 3
  )
```
 
# 관련 정보

